<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>FoLabelMaker</AssemblyName>
    <TargetName>FoLabelMaker</TargetName>
    <AssemblyTitle>FoLabelMaker</AssemblyTitle>
    <Product>FoLabelMaker</Product>
    <Authors>Morten Aasheim</Authors>
    <Company>ECIT Peritus AS</Company>
    <Copyright>Copyright (c) ECIT Peritus AS</Copyright>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FoLabelMaker.Core\FoLabelMaker.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
